spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://horton.db.elephantsql.com:5432/orbuujnl?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect