    #driverClassName: com.mysql.cj.jdbc.Driver
    #url:  jdbc:postgresql://horton.db.elephantsql.com:5432/orbuujnl?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    #url: jdbc:mysql://localhost:3306/river_data_nimh?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    #url: jdbc:postgresql://localhost:5432/river_data_nimh?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    #database-platform: org.hibernate.dialect.MySQLDialect

    spring:
      datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://db.pgygawkwarigmvuiurqn.supabase.co:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${USERNAME}
        password: ${PASSWORD}
      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    server:
      port: 8080
